name: Bersihkan - Hapus cache dan artefak

on:
  # Memungkinkan Anda menjalankan alur kerja ini secara manual dari tab Actions
  workflow_dispatch:

  schedule:
    # Setiap hari pukul 1 pagi
    - cron: '0 1 * * *'

jobs:
  hapus-artefak-lama:

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Bersihkan semua artefak
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 3d # '<jumlah> <unit>', misalnya 5 hari, 2 tahun, 90 detik, diuraikan oleh Moment.js
          GITHUB_TOKEN: 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
