name: Bersihkan - Hapus semua artefak yang berusia di atas 3 hari

on:
  # Memungkinkan Anda menjalankan alur kerja ini secara manual dari tab Actions
  workflow_dispatch:

  schedule:
    # Setiap hari pada pukul 01.00
    - cron: '0 1 * * *'

jobs:
  hapus-artefak-lama:

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Bersihkan semua artefak
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 3d # '<jumlah> <unit>', misalnya 3 hari, 2 minggu, 90 detik, diuraikan oleh Moment.js
          # Input opsional
          # skip-tags: true
          # skip-recent: 5
