name: BUILD WALLPAPER

env:
  # Nama modul utama pada repository
  main_project_module: app

  # Nama Play Store
  playstore_name: NEXEAT WALLPAPER

  # Nama packagename yang baru
  new_package_name: "$APP_DOMAIN.$APP_PLAY_CONSOLE.$APP_NAME"

on:
  push:
    branches:
      - 'release/**'

  # Memungkinkan menjalankan workflow secara manual dari tab Actions
  workflow_dispatch:

jobs:
  build_and_rename:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set Current Date Sebagai Variable Lingkungan
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name Sebagai Variable Lingkungan
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Lihat 'Supported distributions' untuk opsi yang tersedia
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Jalankan Build APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      # Jalankan Build APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      # Jalankan Build AAB Release
      # Dicatat untuk build modul utama [main_project_module]:bundleRelease
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Ubah Nama Folder Packagename
      - name: Rename folder packagename
        run: mv app/src/androidTest/java/com/frogobox/githubaction app/src/androidTest/java/${{ env.new_package_name }}

      # Upload Build Artifact APK Debug
      # Dicatat untuk Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      # Dicatat untuk Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      # Dicatat untuk Output [main_project_module]/build/outputs/bundle/release/
      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
